export const AUTH_MESSAGES = {
  // ─── Success Messages ──────────────────────────────────────────────────────
  SIGNUP_SUCCESS: 'An OTP has been sent to your email. Please check your inbox to verify your account.',
  LOGIN_SUCCESS: (name: string) => `Welcome back, ${name}! Logged in successfully.`,
  VERIFY_SUCCESS: (name: string) => `Welcome to our platform, ${name}. Your account is now verified.`,
  OTP_SENT: 'A fresh OTP has been sent to your email. Please check your inbox.',
  PASSWORD_RESET_SUCCESS: 'Password reset successfully. You can now login with your new password.',
  PASSWORD_CHANGED_SUCCESS: 'Password changed successfully. Please log in again with your new credentials.',
  ACCOUNT_DELETED_SUCCESS: 'Your account has been deleted successfully. We are sorry to see you go.',
  TOKEN_REFRESHED: 'Session token refreshed successfully.',
  OTP_VERIFIED_RESET: 'OTP verified. You may now reset your password.',

  // ─── Error Messages ────────────────────────────────────────────────────────
  INVALID_CREDENTIALS: 'The email or password you entered is incorrect. Please try again.',
  ACCOUNT_NOT_FOUND: 'No account found with this email address.',
  ACCOUNT_LOCKED: (minutes: number) => `Your account is temporarily locked due to too many failed attempts. Try again in ${minutes} minute(s).`,
  ACCOUNT_RESTRICTED: 'Your account has been restricted by an administrator. Please contact support.',
  ACCOUNT_DELETED: 'This account has been deleted. Please contact support if this is an error.',
  UNVERIFIED_ACCOUNT: 'Your account is not verified. An OTP has been sent to your email.',
  ADMIN_ONLY_LOGIN: 'Access denied. You are not authorized to login as an administrator.',
  PASSWORDS_DO_NOT_MATCH: 'The new passwords you entered do not match.',
  PASSWORD_SAME_AS_OLD: 'Your new password cannot be the same as your old password.',
  OLD_PASSWORD_INCORRECT: 'The current password you provided is incorrect.',
  SESSION_EXPIRED_PASSWORD: 'Your session has expired due to a recent password change. Please login again.',
  INVALID_REFRESH_TOKEN: 'Invalid or expired session. Please login again.',
  REFRESH_TOKEN_EXPIRED: 'Your session has expired. Please login again to continue.',
  OTP_LIMIT_REACHED: 'Maximum OTP request limit reached. Please try again in 15 minutes.',
  OTP_COOLDOWN: (seconds: number) => `Please wait ${seconds} seconds before requesting a new OTP.`,
  OTP_EXPIRED: 'The OTP has expired. Please request a new one.',
  OTP_INVALID: 'The verification code you entered is invalid.',
  OTP_TOO_MANY_ATTEMPTS: 'Too many failed OTP attempts. Please request a new one.',
  SESSION_INVALID: 'Invalid or expired session. Please verify your account again.',
  ACTION_BLOCKED_LOCKOUT: (minutes: number) => `Security lockout active. Action blocked. Try again in ${minutes} minute(s).`,
} as const
